### ISSUE TITLE
Animate history.replace()

### ISSUE THREAD

**Issue by greenimpala** [Traviskn/react-router-native-stack#14]
Due to the limitations of the history API, it is not possible to route BACK to a specified route PATH whilst having it animate using the appropriate back transition. Instead, `go(-n)` must be used which is fragile. Is there any way to support this feature?

I was wondering if we could use the `REPLACE` action from `history.replace(path)` to trigger the back animation and have this as a togglable option. I.e `animateOnReplace: Bool`. 

I would be happy to look at this @Traviskn if you're in agreement!

**Comment by Traviskn** [comment]
This sounds like a great idea!

I'm wondering if it would be useful to be able to configure either a forward (push) or backward (pop) transition on replace. Maybe a prop like `replaceTransitionType` where the default is `'none'` and the other two options are `'push'` and `'pop'`. Any thoughts?

**Comment by greenimpala** [comment]
@Traviskn yes thats a great idea! I will have a look at getting this implemented tomorrow 👍

**Comment by greenimpala** [comment]
Done. See #16.
