### ISSUE TITLE
Disable wiping back through the route stack 

### ISSUE THREAD

**Issue by tonyneel923** [Traviskn/react-router-native-stack#15]
Is this possible to disable? Pretty cool component really nice job on it!

**Comment by Traviskn** [comment]
Hi @tonyneel923, thanks for checking out this project!

Yes, you can disable this using the `gestureEnabled` prop.  By default it's set to true, but if you pass in `<Stack gestureEnabled={false}>` then the stack component will no longer allow swiping to navigate back.

I realize that I've completely forgotton to document this, so I'll try to get an update to the README today.  Let me know if you run into any trouble with the `gestureEnabled` prop!
