### ISSUE TITLE
Render before push a new page

### ISSUE THREAD

**Issue by wangbourne** [Traviskn/react-router-native-stack#18]
I noticed there's a blank page during pushing animation. Can push begins after finishing rendering of new page.

![3](https://user-images.githubusercontent.com/2090084/37439347-72dde61e-2843-11e8-90f9-b5f8c8227d93.gif)

**Comment by Traviskn** [comment]
It's hard to say what is causing the blank page during this animation. It could be that the next page has some expensive code running that is blocking the transition, or it could be that the next page needs to indicate some kind of loading state while waiting for new data to come in.
