### ISSUE TITLE
Typescript typing supoort

### ISSUE THREAD

**Issue by wangbourne** [Traviskn/react-router-native-stack#19]
I'm very interested in this project. Any plan to support Typescript support?

**Comment by Traviskn** [comment]
Thanks for your interest!  I've never worked with Typescript, so I don't have any plans yet. I imagine that other users might also want Flowtype support.  I don't want to re-write this project in either Typescript or Flowtype, but I would be open to any pull requests adding Typescript and/or Flowtype type definitions to help out users who need it.
