### ISSUE TITLE
Feature: Transition per route

### ISSUE THREAD

**Issue by ptfly** [Traviskn/react-router-native-stack#2]
First of all, very promising library and much appreciated you're sharing it.
Any suggestions how can I implement different transition types for certain routes?

**Comment by Traviskn** [comment]
Hi @ptfly, thanks for your kind words!  I was working on adding more configuration options to the routes in the stack today, and I just pushed an update that should support configuring different transition types for certain routes.  I've documented it in the README here: https://github.com/Traviskn/react-router-native-stack#customizing-animation-type-per-route

Let me know if that works for you!

**Comment by ptfly** [comment]
Thanks, I’ll check it out asap!

**Comment by Traviskn** [comment]
This feature is supported now, so I'm going to close this issue.  Let me know if you run into any issues with configuring transitions per route!
