### ISSUE TITLE
flexDirection issue in stackView styles

### ISSUE THREAD

**Issue by wangbourne** [Traviskn/react-router-native-stack#20]
I can see a problem like attached because we have `flexDirection: 'column-reverse'`, in `styles.js`.

If I change to `flexDirection: 'column'`, it works. 

Is there any special reason to set 'column-reverse' rather than 'column'?

![image](https://user-images.githubusercontent.com/2090084/37445595-a62625ba-2864-11e8-93c0-cda42523ca34.png)

**Comment by Traviskn** [comment]
I realized this isn't well-documented, but you can pass in a `stackViewStyle` prop to the `Stack` to override the `flexDirection` style for your needs.

The reason that styling is here is that I was working on adding some built-in header support to the `Stack`, and I wanted to make sure the header was always rendered on the top layer and not hidden behind other components.  I noticed that `react-navigation` always renders their header last in the list of components and then uses `flexDirection: 'column-reverse'` to put it at the top of the screen, so I put in this styling to experiment with that strategy. (see their code and comments here: https://github.com/react-navigation/react-navigation/blob/fcbf78e658f5e5c6cc4b7f2ef0ec345fff8fb448/src/views/StackView/StackViewLayout.js#L456)

I'll probably take another look at this though and see if it's really necessary
