### ISSUE TITLE
Header title would not work with wrapped children

### ISSUE THREAD

**Issue by gabrielbull** [Traviskn/react-router-native-stack#22]
https://github.com/Traviskn/react-router-native-stack/blob/c6a0e3a7e09f9b7d67db498853c60784f662685c/lib/StackTransitioner.js#L267

Would not work in this instance:

```
class MyRoute extends Component {
    render () {
        return <Route title='My amazing title!!!' />
    }
}

class Router extends Component {
    render () {
        return (
            <Stack renderHeader>
               <MyRoute />
            </Stack>
        )
    }
}

```

**Comment by Traviskn** [comment]
Hi @gabrielbull! Like the `Switch` in `react-router`, the `Stack` only supports `Route` components as children.  A lot more things than the title would break if you used wrapped children like in your example.  Instead, you should return your component in the `render` prop of the route, pass your component to the `component` prop of the route, or pass it to the `children` prop of the route.  See the docs for the `Route` component here: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/Route.md

**Comment by gabrielbull** [comment]
Makes sense. I'm not using the default header but I'm trying to make sure it wouldn't cause issues. Do you intend to have all header props in the Router component? I.E. title, right components, left components, etc. 

An alternate approach would be to use a decorator like `withRouter` or a nested component like [React Helmet](https://github.com/nfl/react-helmet) does. 

Here's a decorator example, just for discussion:

```
function withHeader (title: string) {
  return function (WrappedComponent) {
    class Wrapper extends React.Component {
      public static contextTypes = {
        _reactRouterNativeStackSetTitle: PropTypes.func
      }

      public componentDidMount () {
        if (this.context._reactRouterNativeStackSetTitle) {
          this.context._reactRouterNativeStackSetTitle(title)
        }
      }

      public render () {
        return <WrappedComponent {...this.props}/>
      }
    }
    return Wrapper
  }
}

const Home = () => (
  <Tex>
    Home
  </Text>
)

export default withHeader('Home')(Home)
```

**Comment by gabrielbull** [comment]
Or it could be like so:

```js
<Route path='/' header={<Header title='Home' />} />
```
