### ISSUE TITLE
Updating state/mounting

### ISSUE THREAD

**Issue by ThrowJojo** [Traviskn/react-router-native-stack#3]
First of all thank you so much for creating such an amazing library. It's so useful for bringing life to a project with react-router-native. I also realize this library is still in very early stages. I'm writing because I released a beta version for an app on Android with react-router-native-stack in it and I was getting some cryptic errors like these in my Crashlytics:

`Fatal Exception: com.facebook.react.common.JavascriptException: Attempted to update component `i` that has already been unmounted (or failed to mount).`

I checked the minified release bundle file for the app and found 'i', it looks like it has something to do with react-router-native-stack setting state:
`i.afterPan=function(){i.isPanning=!1,i.setState({previousLocation:{},transition:null}),i.props.history.action===P.POP&&i.setState({routeAnimationType:i.state.children.props.animationType})
`
The stack for the app is just react-router-native and mobx. I have an entry file called App.js that looks something like this:

```javascript 
export default class App extends Component {
  render() {
    return (
      <Provider todoStore={todoStore} settingsStore={settingsStore}>
        <NativeRouter>
          <View style={Styles.container}>
            <BackButton />
            <Stack animationType="slide-vertical">
              <Route exact path="/" component={SplashScreen} />
              <Route path="/todo" component={TodoScreen} />
              <Route path="/add" component={AddScreen} />
              <Route path="/settings" component={SettingsScreen} />
            </Stack>
          </View>
        </NativeRouter>
      </Provider>
    );
  }
}
```

I couldn't actually re-produce this issue on any of my own devices, I've only seen it on Crashlytics/Android Vitals. Is there an issue with how I'm implementing the Stack component?

**Comment by Traviskn** [comment]
Hi @ThrowJojo, thanks for the bug report!  I don't think you're doing anything wrong on your end.  It looks like the Stack component is getting unmounted during an animation, I probably need to add some logic to cancel animations in `componentWillUnmount`.  I'll be looking into this today

**Comment by Traviskn** [comment]
I added logic to cancel animations on componentWillUnmount and not call set state - version 0.0.5 _should_ stop these errors you're seeing.  Let me know if you still run into them on the new version
