### ISSUE TITLE
Nested stacks

### ISSUE THREAD

**Issue by rstuven** [Traviskn/react-router-native-stack#30]
For example, an outer stack using 'cube' with an inner stack using 'slide-horizontal'. The inner stack should be reactive to changes in its children routes, but the outer stack not.

**Comment by Traviskn** [comment]
This functionality should be supported via a `key` prop on your route component: https://github.com/Traviskn/react-router-native-stack#nested-routes

This assumes that you have a component structure where inner stack is being rendered by a route component in the outer stack

**Comment by rstuven** [comment]
Thanks, I was missing that, but also it wasn't working for me in the first place when there were no matching child routes (because a series of errors when children or previousChildren were null). I'll send you a PR with the fix.

**Comment by Traviskn** [comment]
Thanks for your PR!
