### ISSUE TITLE
Warning: Encountered two children with the same key

### ISSUE THREAD

**Issue by Dallas62** [Traviskn/react-router-native-stack#4]
Hi!

After some tests on my application, I saw a warning coming about duplicate keys.
After some investigations, I saw it comes from the render function of StackTransitioner.
    in RCTView (at View.js:113)
    in View (at StackTransitioner.js:264)
    in RCTView (at View.js:113)
    in View (at StackTransitioner.js:263)
    in StackTransitioner (at Stack.js:54)

It appends when you re-render the component, in my case, in conjunction with:
https://github.com/react-native-community/react-native-side-menu
(using BACK, then OPEN MENU quickly).

I will send you a PR to show you how I fixed it (probably not the right solution)

**Comment by Traviskn** [comment]
Thanks for the bug report @Dallas62!  I appreciate your pull request.  Guarding against identical location keys is something I tried to do in my `componentWillRecieveProps` method but it seems that it's not working!  Do you happen to have some example code that reproduces the warning?

**Comment by Dallas62** [comment]
I will not have time to make a exemple of code for now, but I tried another solution that is working:
```
  shouldComponentUpdate(nextProps, nextState) {
    return (nextProps.location || {}).key !== (nextState.previousLocation || {}).key;
  }
```

**Comment by Traviskn** [comment]
Alright, I think I figured how to fix my logic to prevent the state from becoming inconsistent, let me know if you still run into problems with v0.0.5
